language: node_js
node_js:
  - 18.15.0

services:
  - docker

branches:
  only:
    - qa
    - production

jobs:
  include:
    - stage: docker build
      if: (branch = qa or branch = production)
      before_install:
        - if [[ $TRAVIS_BRANCH == "qa" ]];
          then
          export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_QA};
          export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_QA};
          export ENV="qa";
          fi
        - if [[ "$TRAVIS_BRANCH" == "production" ]];
          then
          export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PRODUCTION};
          export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PRODUCTION};
          export ENV="production";
          fi
      env:
        - ECR_URL=491147561046.dkr.ecr.us-east-1.amazonaws.com/nyplglobalheader
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_REGION=us-east-1
      install:
        - pip install --user awscli
        - export LOCAL_TAG_NAME="${ENV}-latest"
      script:
        - eval $(aws ecr get-login --no-include-email --region us-east-1)
        - DOCKER_BUILDKIT=1 docker build -t "$LOCAL_TAG_NAME" --secret id=AWS_ACCESS_KEY_ID --secret id=AWS_SECRET_ACCESS_KEY" .
        - docker tag "$LOCAL_TAG_NAME" "$ECR_URL:$LOCAL_TAG_NAME"
        - docker push "$ECR_URL:$LOCAL_TAG_NAME"

    - stage: deploy qa
      if: branch IN (qa) AND type != pull_request
      env:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_QA
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_QA
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_REGION=us-east-1
        - CLUSTER_NAME=nyplorg-globalheader-qa
      install:
        - pip install --user awscli
      script:
        - aws ecs update-service --cluster $CLUSTER_NAME --service $CLUSTER_NAME --force-new-deployment

    - stage: deploy production
      if: branch IN (production) AND type != pull_request
      env:
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_REGION=us-east-1
        - CLUSTER_NAME=nyplorg-globalheader-production
      install:
        - pip install --user awscli
      script:
        - aws ecs update-service --cluster $CLUSTER_NAME --service $CLUSTER_NAME --force-new-deployment

env:
  global:
    # AWS dev
    - secure: OhqeYc2DwKTLG4ywviFdiZextb+8Mae+XuIXYKX1lfeFIiQC9tflAmCz5y/TzKp+Mz9BfZwo7uZeW0XmMlVIKAhqjIShC4gM7cqX9p1xEkWUj6OwRtC0yT2rlv210NT/tsPDnTZo3KdD/+dBeNlknOax5H0/EqMqhw5pKJuLj6fLn3Tjgrgj4OFQR/JhFCbrCzpbAzJmlwGqP3QOlX181dbmPkUgQEuS2R05qujCwsWrzk0X9Kcm7BYCoxI1PfymDV4ZY0sR9TZGSqziRQsAIyMgm1yIY3o9sffar7oooxBqySU2Del/CoKFr1xfecdDL5xd5PbqpHFsUh3swZu2Qny5Ef4XYq6y0YOdQ8xC7bYUJEgvRv6EZxo7ZsS+eqCx3HIWtQyKXrT7qU8ChJtcCDj8jRZKrKtmR6xV3orlZCIzj4WVBj8L6IAd5ypUCkk+RrdhHFN69o19dR77ZIQ4dsX4cqQfwO+LnQtefHpF5kLS6vYJqd5WifAl6UA+84KfDspz32cIEXuuUqJqNGcG/0Ef1OTif7beENxkGsYOh1ujxG/tyW44ZeYW8Ep5jOEHa8iUCH5m3pvmnQBsgFvAxe1+lDnA1+pqIJus3gYKeByBEZoo06haOynsDBY4xNQZxtiC2V6uKzgUgKkrQf2iaitvqH9NMMzKZuGcBvwA648=
    # AWS prod
    - secure: cubP7e/Qs/LH31WGQTt3QSYgsBECmaZH4JOUSYVAOD8Axk0YTpCFVBbIzXd7XAfkEu7JMlDD2pvoc0WaIUAwDjh4wQ6Wx0wMpXfsREurdtEqkXyzdy8ECLSDix1rCFirlaEgDL0Auvp9my3hNpq16+NBP+08RizfRVzcKyaovw6e+VP6bKkZOk3m6dkTwH/u5iLR99oi+Q9s/KLHZmPMN8/R9p2OeXyWpR02IVOwkyywv/7A4D+5vd//+B7L1sn/+BcKVQvxDUaUiZdSXszd5HdwTv/zIozWn9rlontx92XQs7Cn6aMUPVxY0zH/4bA8kC54UrBxYN3eLyEWdH4DSz7FjVtO7v3Gh71659+kUjur0piFvYYDHIxWjRMue8vuo7Dd7jMdDimVBmBpfk2Cs6gp538RDC7FYE9cNpvE1m9bL8GcVzhp7iaGnFhqKl/zwx4V8zwb6UIbw10AkhowU/fxBtm9Y5jA9owgOGKXDrTSaOo83LK2uM37aOgdzxozKT1/e9rmBH+ZSvfGKo4G/sG2aOyhjRgQtB2dBaRJxySW6VJi6hldBd/idfkIw7oTE7oZFjBoRXZHrVgqr+qt/bmNk+eq2yZYgmm0c5lXjowsaGtL+qFcUSsU7mg1NVEQReYOt/xJa4tb7kcp7DOTfTqky1wl5HgD98ds1epkSao=

after_success: echo "Deploying $TRAVIS_BRANCH"
