# For all PRs, this workflow will
#     - Install deps
#     - Test
name: CI

on: 
    # will run on all PRs that are opened or updated (synchronized)
    pull_request:
      types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache and install node modules
        uses: bahmutov/npm-install@v1
      - name: Test
        run: npm run test
