# For all PRs, this workflow will
#     - Install deps
#     - Test
name: CI

on:
  # will run on all PRs that are opened or updated (synchronized)
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run test
